language: python
dist: xenial

python:
- '3.6'
- '3.7'
- '3.8'

before_install:
#  - chmod +x .ci/travis_build_wheels.sh
  - chmod +x .ci/travis_deploy.sh

script:
  - echo "skipping tests"
#  - .ci/travis_build_wheels.sh
  - .ci/travis_deploy.sh
